services:
  gho_database:
    image: mysql
    container_name: gho_database
    environment:
      MYSQL_ROOT_PASSWORD: ah789y89f90128aj348df
      MYSQL_DATABASE: gho_blog   
      MYSQL_USER: gho_blog
      MYSQL_PASSWORD: ah789y89f90128aj348df
      MYSQL_TCP_PORT: 3309
    ports:
      - 3309:3309
    volumes:
     - GhoDatabaseData:/var/lib/mysql
    networks:
     - ghoBackendNetwork
     
  gho_backend:
    image: openjdk:17
    container_name: gho_backend
    ports:
      - 8080:8080
    depends_on:
      - gho_database
    volumes:
      - ./backend/ghoblog/target/ghoblog-1.0.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - ghoBackendNetwork


volumes:
  GhoDatabaseData:
  
networks:
  ghoBackendNetwork: