services:
  gho_database:
    image: postgres
    container_name: gho_database
    environment:
      POSTGRES_DB: gho_blog   
      POSTGRES_USER: gho_blog
      POSTGRES_PASSWORD: ah789y89f90128aj348df
      PGDATA: /var/lib/postgresql/data/db_files/
    ports:
      - 5432:5432
    volumes:
     - GhoDatabaseData:/var/lib/postgresql/data
    networks:
     - ghoBackendNetwork
     
  gho_backend:
    image: openjdk:17
    container_name: gho_backend
    ports:
      - 8080:8080
    depends_on:
      - gho_database
    volumes:
      - ./backend/ghoblog.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - ghoBackendNetwork


volumes:
  GhoDatabaseData:
  
networks:
  ghoBackendNetwork: